from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth','0012_alter_user_first_name_max_length')]
    operations = [
        migrations.CreateModel(name='Exercise', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=160,unique=True)),('muscle_group',models.CharField(blank=True,max_length=80)),('description',models.TextField(blank=True)),('source',models.CharField(default='custom',max_length=40)),('external_id',models.CharField(blank=True,max_length=80))], options={'ordering':['name']}),
        migrations.CreateModel(name='WorkoutPlan', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('day_of_week',models.PositiveSmallIntegerField(choices=[(1,'Monday'),(2,'Tuesday'),(3,'Wednesday'),(4,'Thursday'),(5,'Friday'),(6,'Saturday'),(7,'Sunday')])),('name',models.CharField(blank=True,max_length=120)),('duration_minutes',models.PositiveIntegerField(default=0)),('is_rest_day',models.BooleanField(default=False)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='workout_plans',to=settings.AUTH_USER_MODEL))], options={'ordering':['day_of_week']}),
        migrations.CreateModel(name='UserGoal', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('weekly_calorie_target',models.PositiveIntegerField(default=2500)),('updated_at',models.DateTimeField(auto_now=True)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='goal',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='ProgressPhoto', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('captured_at',models.DateTimeField(auto_now_add=True)),('image',models.ImageField(upload_to='progress_photos/%Y/%m/%d/')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='progress_photos',to=settings.AUTH_USER_MODEL))], options={'ordering':['-captured_at']}),
        migrations.CreateModel(name='WorkoutExercise', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('position',models.PositiveIntegerField(default=0)),('sets',models.PositiveIntegerField(default=3)),('reps',models.PositiveIntegerField(default=10)),('weight_kg',models.DecimalField(decimal_places=2,default=0,max_digits=7)),('calories_per_set',models.DecimalField(decimal_places=2,default=0,max_digits=7)),('exercise',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='workout_items',to='fitness.exercise')),('workout',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='exercises',to='fitness.workoutplan'))], options={'ordering':['position','id']}),
        migrations.CreateModel(name='WorkoutSession', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('date',models.DateField()),('duration_minutes',models.PositiveIntegerField(default=0)),('completed',models.BooleanField(default=False)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='sessions',to=settings.AUTH_USER_MODEL)),('workout',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='sessions',to='fitness.workoutplan'))], options={'ordering':['-date']}),
        migrations.CreateModel(name='ExerciseLog', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('completed',models.BooleanField(default=False)),('sets_completed',models.PositiveIntegerField(default=0)),('reps_completed',models.PositiveIntegerField(default=0)),('weight_kg',models.DecimalField(decimal_places=2,default=0,max_digits=7)),('session',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='logs',to='fitness.workoutsession')),('workout_exercise',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='logs',to='fitness.workoutexercise'))]),
        migrations.AddConstraint(model_name='workoutplan',constraint=models.UniqueConstraint(fields=('user','day_of_week'),name='unique_user_workout_day')),
        migrations.AddConstraint(model_name='workoutsession',constraint=models.UniqueConstraint(fields=('user','workout','date'),name='unique_session_per_day')),
        migrations.AddConstraint(model_name='exerciselog',constraint=models.UniqueConstraint(fields=('session','workout_exercise'),name='unique_exercise_log')),
    ]
